---
- name: Install system packages
  become: yes
  apt:
    name:
      - git
      - python-pip
    state: present
    update_cache: true
  tags:
    - packages

# TODO: python2 -m pip install supervisor

- name: Install system python packages
  become: yes
  pip:
    name:
      - boto
      - python-dateutil
      - boto3
  tags:
    - aws
    - s3

- name: Copy machine info
  template:
    src: asv-machine.json.j2
    dest: /home/{{ ansible_user }}/.asv-machine.json

- name: Copy master runner
  template:
    src: benchmark_runner.sh
    dest: /usr/local/bin/benchmark_runner
    mode: 0755
  become: yes
  tags:
    - runners

- name: Copy master publisher
  template:
    src: publish.sh.j2
    dest: /usr/local/bin/publish
    mode: 0755
  become: yes
  tags:
    - publish

- name: Ensure runners directory
  file:
    path: /home/{{ ansible_user }}/runners
    state: directory
  tags:
    - runners

- name: Copy runner script
  template:
    src: run.sh.j2
    dest: /home/{{ ansible_user }}/runners/{{ item.project }}.sh
    mode: 0755
  with_items: "{{ repositories }}"
  tags:
    - runners

- name: Download repositories
  git:
    repo: "{{ item.url }}"
    dest: "/home/{{ ansible_user }}/{{ item.project }}"
  with_items: "{{ repositories }}"

- name: Clone collections repository
  git:
    # use SSH for deploy key
    repo: git@github.com:asv-runner/asv-collection.git
    dest: /home/{{ ansible_user }}/asv-collection
  tags:
    - publish
    - collection

- name: Update index.html
  template:
    src: index.html.j2
    dest: /home/{{ ansible_user }}/asv-collection/index.html
  tags:
    - publish

- name: Copy airflow script
  template:
    src: run_dag.py.j2
    dest: /home/{{ ansible_user }}/airflow/dags/run_dag.py
  tags:
    - airflow

- name: Copy airflow startup scripts
  template:
    src: "{{ item }}.j2"
    dest: /home/{{ ansible_user }}/airflow/{{ item }}
    mode: 0755
  with_items:
    - start-webserver
    - start-scheduler
  tags:
    - airflow

- name: Copy supervisor process
  become: yes
  template:
    src: airflow-supervisord-conf.j2
    dest: /etc/supervisor/conf.d/airflow.conf
  tags:
    airflow
